-- ============================================================
-- BANKING TRANSACTION FRAUD DETECTION
-- PostgreSQL - 29 TABLES
-- ============================================================

CREATE SCHEMA IF NOT EXISTS banking;
SET search_path TO banking;

-- ============================================================
-- 1. BRANCH
-- ============================================================

CREATE TABLE branch (
    branchid       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branchcode     VARCHAR(20) NOT NULL UNIQUE,
    branchname     VARCHAR(150) NOT NULL,
    address        VARCHAR(255) NOT NULL,
    city           VARCHAR(100) NOT NULL,
    phone          VARCHAR(20),
    opendate       DATE NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'Active',
    createdat      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_branch_status
        CHECK (status IN ('Active', 'Inactive'))
);


-- ============================================================
-- 2. ROLE
-- ============================================================

CREATE TABLE role (
    roleid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rolename       VARCHAR(100) NOT NULL UNIQUE,
    description    VARCHAR(255),
    status         VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT ck_role_status
        CHECK (status IN ('Active', 'Inactive'))
);


-- ============================================================
-- 3. EMPLOYEE
-- ============================================================

CREATE TABLE employee (
    employeeid     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employeecode   VARCHAR(20) NOT NULL UNIQUE,
    branchid       INTEGER NOT NULL,
    roleid         INTEGER NOT NULL,
    fullname       VARCHAR(150) NOT NULL,
    gender         VARCHAR(10),
    dateofbirth    DATE,
    phone          VARCHAR(20) NOT NULL UNIQUE,
    email          VARCHAR(150) NOT NULL UNIQUE,
    hiredate       DATE NOT NULL,
    salary         NUMERIC(19,2) NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT fk_employee_branch
        FOREIGN KEY (branchid)
        REFERENCES branch(branchid),

    CONSTRAINT fk_employee_role
        FOREIGN KEY (roleid)
        REFERENCES role(roleid),

    CONSTRAINT ck_employee_gender
        CHECK (gender IS NULL OR
               gender IN ('Male','Female','Other','Unknown')),

    CONSTRAINT ck_employee_salary
        CHECK (salary >= 0),

    CONSTRAINT ck_employee_status
        CHECK (status IN ('Active','Inactive'))
);


-- ============================================================
-- 4. SYSTEM_USER
-- ============================================================

CREATE TABLE "system_user" (
    userid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employeeid     INTEGER NOT NULL UNIQUE,
    username       VARCHAR(100) NOT NULL UNIQUE,
    passwordhash   VARCHAR(255) NOT NULL,
    lastlogin      TIMESTAMP,
    isactive       BOOLEAN NOT NULL DEFAULT TRUE,
    createdat      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_system_user_employee
        FOREIGN KEY (employeeid)
        REFERENCES employee(employeeid),

    CONSTRAINT ck_system_user_lastlogin
        CHECK (lastlogin IS NULL OR lastlogin >= createdat)
);


-- ============================================================
-- 5. CUSTOMER
-- ============================================================

CREATE TABLE customer (
    customerid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customercode      VARCHAR(20) NOT NULL UNIQUE,
    fullname          VARCHAR(150) NOT NULL,
    gender            VARCHAR(10),
    dateofbirth       DATE,
    nationalid        VARCHAR(30) UNIQUE,
    phone             VARCHAR(20),
    email             VARCHAR(150),
    address           VARCHAR(255),
    occupation        VARCHAR(100),
    customertype      VARCHAR(30),
    createddate       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status            VARCHAR(20) NOT NULL DEFAULT 'Active',
    customersegment   VARCHAR(30),

    CONSTRAINT ck_customer_gender
        CHECK (gender IS NULL OR
               gender IN ('Male','Female','Other','Unknown')),

    CONSTRAINT ck_customer_status
        CHECK (status IN ('Active','Inactive','Blocked'))
);


-- ============================================================
-- 6. CUSTOMER_ONLINE_ACCOUNT
-- ============================================================

CREATE TABLE customer_online_account (
    onlineaccountid   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customerid        BIGINT NOT NULL UNIQUE,
    username          VARCHAR(100) NOT NULL UNIQUE,
    passwordhash      VARCHAR(255) NOT NULL,
    registereddate    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastlogin         TIMESTAMP,
    isactive          BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_online_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT ck_online_lastlogin
        CHECK (lastlogin IS NULL OR lastlogin >= registereddate)
);


-- ============================================================
-- 7. CUSTOMER_DEVICE
-- ============================================================

CREATE TABLE customer_device (
    deviceid          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customerid        BIGINT NOT NULL,
    devicecode        VARCHAR(100) NOT NULL UNIQUE,
    devicetype        VARCHAR(30) NOT NULL,
    devicename        VARCHAR(100),
    operatingsystem   VARCHAR(80),
    firstseenat       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastseenat        TIMESTAMP,
    istrusted         BOOLEAN NOT NULL DEFAULT FALSE,
    status            VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT fk_device_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT uq_customer_device
        UNIQUE (customerid, deviceid),

    CONSTRAINT ck_device_type
        CHECK (devicetype IN ('Mobile','Tablet','Desktop','Other')),

    CONSTRAINT ck_device_status
        CHECK (status IN ('Active','Blocked','Removed')),

    CONSTRAINT ck_device_time
        CHECK (lastseenat IS NULL OR lastseenat >= firstseenat)
);


-- ============================================================
-- 8. LOGIN_EVENT
-- ============================================================

CREATE TABLE login_event (
    logineventid    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customerid      BIGINT NOT NULL,
    deviceid        BIGINT,
    logintime       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipaddress       VARCHAR(45),
    status          VARCHAR(20) NOT NULL,
    failurereason   VARCHAR(255),

    CONSTRAINT fk_login_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT fk_login_device
        FOREIGN KEY (customerid, deviceid)
        REFERENCES customer_device(customerid, deviceid),

    CONSTRAINT ck_login_status
        CHECK (status IN ('Success','Failed','Blocked')),

    CONSTRAINT ck_login_reason
        CHECK (
            (status = 'Success' AND failurereason IS NULL)
            OR
            (status IN ('Failed','Blocked') AND failurereason IS NOT NULL)
        )
);


-- ============================================================
-- 9. ACCOUNT_TYPE
-- ============================================================

CREATE TABLE account_type (
    accounttypeid   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typename        VARCHAR(100) NOT NULL UNIQUE,
    minbalance      NUMERIC(19,2) NOT NULL DEFAULT 0,
    interestrate    NUMERIC(8,4) NOT NULL DEFAULT 0,
    description     VARCHAR(255),
    status          VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT ck_account_type_minbalance
        CHECK (minbalance >= 0),

    CONSTRAINT ck_account_type_interest
        CHECK (interestrate >= 0),

    CONSTRAINT ck_account_type_status
        CHECK (status IN ('Active','Inactive'))
);


-- ============================================================
-- 10. BANK_ACCOUNT
-- ============================================================

CREATE TABLE bank_account (
    accountid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountnumber     VARCHAR(30) NOT NULL UNIQUE,
    branchid          INTEGER NOT NULL,
    accounttypeid     INTEGER NOT NULL,
    opendate           DATE NOT NULL,
    balance            NUMERIC(19,2) NOT NULL DEFAULT 0,
    currency           CHAR(3) NOT NULL DEFAULT 'VND',
    status             VARCHAR(20) NOT NULL DEFAULT 'Active',
    createdat          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat          TIMESTAMP,
    accountcategory    VARCHAR(20) NOT NULL,

    CONSTRAINT fk_bank_account_branch
        FOREIGN KEY (branchid)
        REFERENCES branch(branchid),

    CONSTRAINT fk_bank_account_type
        FOREIGN KEY (accounttypeid)
        REFERENCES account_type(accounttypeid),

    CONSTRAINT ck_bank_account_currency
        CHECK (currency = 'VND'),

    CONSTRAINT ck_bank_account_status
        CHECK (status IN ('Active','Frozen','Closed')),

    CONSTRAINT ck_bank_account_category
        CHECK (accountcategory IN ('CUSTOMER','INTERNAL')),

    CONSTRAINT ck_bank_account_updated
        CHECK (updatedat IS NULL OR updatedat >= createdat)
);


-- ============================================================
-- 11. ACCOUNT_HOLDER
-- ============================================================

CREATE TABLE account_holder (
    accountholderid   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid         BIGINT NOT NULL,
    customerid        BIGINT NOT NULL,
    holdertype        VARCHAR(30) NOT NULL,
    startdate         DATE NOT NULL,
    enddate           DATE,
    status            VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT fk_holder_account
        FOREIGN KEY (accountid)
        REFERENCES bank_account(accountid),

    CONSTRAINT fk_holder_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT ck_holder_type
        CHECK (holdertype IN (
            'PRIMARY_OWNER',
            'JOINT_OWNER',
            'AUTHORIZED_USER'
        )),

    CONSTRAINT ck_holder_status
        CHECK (status IN ('Active','Inactive')),

    CONSTRAINT ck_holder_dates
        CHECK (
            (status = 'Active' AND enddate IS NULL)
            OR
            (status = 'Inactive'
             AND enddate IS NOT NULL
             AND enddate >= startdate)
        )
);

CREATE UNIQUE INDEX ux_account_holder_active
ON account_holder(accountid, customerid)
WHERE status = 'Active';

CREATE UNIQUE INDEX ux_account_primary_owner
ON account_holder(accountid)
WHERE status = 'Active'
AND holdertype = 'PRIMARY_OWNER';


-- ============================================================
-- 12. ACCOUNT_STATUS_HISTORY
-- ============================================================

CREATE TABLE account_status_history (
    historyid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountid       BIGINT NOT NULL,
    oldstatus       VARCHAR(20),
    newstatus       VARCHAR(20) NOT NULL,
    changeddate     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changedbytype   VARCHAR(20) NOT NULL,
    employeeid      INTEGER,
    reason          VARCHAR(255),

    CONSTRAINT fk_account_history_account
        FOREIGN KEY (accountid)
        REFERENCES bank_account(accountid),

    CONSTRAINT fk_account_history_employee
        FOREIGN KEY (employeeid)
        REFERENCES employee(employeeid),

    CONSTRAINT ck_account_history_old
        CHECK (oldstatus IS NULL OR
               oldstatus IN ('Active','Frozen','Closed')),

    CONSTRAINT ck_account_history_new
        CHECK (newstatus IN ('Active','Frozen','Closed')),

    CONSTRAINT ck_account_history_actor
        CHECK (changedbytype IN ('Employee','System'))
);


-- ============================================================
-- 13. CARD
-- ============================================================

CREATE TABLE card (
    cardid          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cardnumber      VARCHAR(30) NOT NULL UNIQUE,
    accountid       BIGINT NOT NULL,
    issuedate       DATE NOT NULL,
    expirydate      DATE NOT NULL,
    cardtype        VARCHAR(30) NOT NULL,
    pinhash         VARCHAR(255) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'Active',
    dailylimit      NUMERIC(19,2) NOT NULL,
    customerid      BIGINT NOT NULL,

    CONSTRAINT fk_card_account
        FOREIGN KEY (accountid)
        REFERENCES bank_account(accountid),

    CONSTRAINT fk_card_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT ck_card_dates
        CHECK (expirydate > issuedate),

    CONSTRAINT ck_card_limit
        CHECK (dailylimit > 0),

    CONSTRAINT ck_card_status
        CHECK (status IN ('Active','Blocked','Expired','Closed'))
);


-- ============================================================
-- 14. TRANSACTION_TYPE
-- ============================================================

CREATE TABLE transaction_type (
    transactiontypeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typecode           VARCHAR(30) NOT NULL UNIQUE,
    typename           VARCHAR(100) NOT NULL UNIQUE,
    description        VARCHAR(255),
    status             VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT ck_transaction_type_code
        CHECK (typecode IN (
            'TRANSFER',
            'DEPOSIT',
            'WITHDRAWAL',
            'LOAN_PAYMENT',
            'OPENING_BALANCE',
            'REVERSAL'
        )),

    CONSTRAINT ck_transaction_type_status
        CHECK (status IN ('Active','Inactive'))
);


-- ============================================================
-- 15. TERMINAL
-- ============================================================

CREATE TABLE terminal (
    terminalid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terminalcode     VARCHAR(40) NOT NULL UNIQUE,
    branchid         INTEGER,
    terminaltype     VARCHAR(20) NOT NULL,
    locationname     VARCHAR(150),
    address          VARCHAR(255),
    status           VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT fk_terminal_branch
        FOREIGN KEY (branchid)
        REFERENCES branch(branchid),

    CONSTRAINT ck_terminal_type
        CHECK (terminaltype IN ('ATM','POS','COUNTER')),

    CONSTRAINT ck_terminal_status
        CHECK (status IN ('Active','Inactive','Maintenance'))
);


-- ============================================================
-- 16. BANK_TRANSACTION
-- ============================================================

CREATE TABLE bank_transaction (
    transactionid           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactioncode         VARCHAR(40) NOT NULL UNIQUE,
    transactiontypeid       INTEGER NOT NULL,
    employeeid              INTEGER,
    terminalid              BIGINT,
    deviceid                BIGINT,
    channel                 VARCHAR(30) NOT NULL,
    amount                  NUMERIC(19,2) NOT NULL,
    fee                     NUMERIC(19,2) NOT NULL DEFAULT 0,
    currency                CHAR(3) NOT NULL DEFAULT 'VND',
    transactiondate         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipaddress               VARCHAR(45),
    latitude                NUMERIC(9,6),
    longitude               NUMERIC(9,6),
    description             VARCHAR(255),
    status                  VARCHAR(20) NOT NULL,
    initiatedbycustomerid   BIGINT,
    cardid                  BIGINT,
    originaltransactionid   BIGINT,

    CONSTRAINT fk_transaction_type
        FOREIGN KEY (transactiontypeid)
        REFERENCES transaction_type(transactiontypeid),

    CONSTRAINT fk_transaction_employee
        FOREIGN KEY (employeeid)
        REFERENCES employee(employeeid),

    CONSTRAINT fk_transaction_terminal
        FOREIGN KEY (terminalid)
        REFERENCES terminal(terminalid),

    CONSTRAINT fk_transaction_customer
        FOREIGN KEY (initiatedbycustomerid)
        REFERENCES customer(customerid),

    CONSTRAINT fk_transaction_card
        FOREIGN KEY (cardid)
        REFERENCES card(cardid),

    CONSTRAINT fk_transaction_original
        FOREIGN KEY (originaltransactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT fk_transaction_device
        FOREIGN KEY (initiatedbycustomerid, deviceid)
        REFERENCES customer_device(customerid, deviceid),

    CONSTRAINT ck_transaction_channel
        CHECK (channel IN (
            'Counter',
            'ATM',
            'POS',
            'MobileBanking',
            'InternetBanking',
            'System'
        )),

    CONSTRAINT ck_transaction_amount
        CHECK (amount > 0),

    CONSTRAINT ck_transaction_fee
        CHECK (fee >= 0),

    CONSTRAINT ck_transaction_currency
        CHECK (currency = 'VND'),

    CONSTRAINT ck_transaction_status
        CHECK (status IN (
            'Pending',
            'Success',
            'Failed',
            'Cancelled'
        )),

    CONSTRAINT ck_transaction_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),

    CONSTRAINT ck_transaction_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);


-- ============================================================
-- 17. TRANSFER_REQUEST
-- ============================================================

CREATE TABLE transfer_request (
    transferrequestid      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionid          BIGINT NOT NULL UNIQUE,
    customerid             BIGINT NOT NULL,
    sourceaccountid        BIGINT NOT NULL,
    destinationaccountid   BIGINT NOT NULL,
    idempotencykey         VARCHAR(100) NOT NULL UNIQUE,
    amount                 NUMERIC(19,2) NOT NULL,
    currency               CHAR(3) NOT NULL DEFAULT 'VND',
    requestedat            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status                 VARCHAR(20) NOT NULL,

    CONSTRAINT fk_transfer_transaction
        FOREIGN KEY (transactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT fk_transfer_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT fk_transfer_source
        FOREIGN KEY (sourceaccountid)
        REFERENCES bank_account(accountid),

    CONSTRAINT fk_transfer_destination
        FOREIGN KEY (destinationaccountid)
        REFERENCES bank_account(accountid),

    CONSTRAINT ck_transfer_accounts
        CHECK (sourceaccountid <> destinationaccountid),

    CONSTRAINT ck_transfer_amount
        CHECK (amount > 0),

    CONSTRAINT ck_transfer_currency
        CHECK (currency = 'VND'),

    CONSTRAINT ck_transfer_status
        CHECK (status IN (
            'Pending',
            'Approved',
            'Rejected',
            'Completed',
            'Failed',
            'Cancelled'
        ))
);


-- ============================================================
-- 18. TRANSACTION_POSTING
-- ============================================================

CREATE TABLE transaction_posting (
    postingid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionid   BIGINT NOT NULL,
    accountid       BIGINT NOT NULL,
    postingtype     VARCHAR(10) NOT NULL,
    amount          NUMERIC(19,2) NOT NULL,
    postingdate     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description     VARCHAR(255),

    CONSTRAINT fk_posting_transaction
        FOREIGN KEY (transactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT fk_posting_account
        FOREIGN KEY (accountid)
        REFERENCES bank_account(accountid),

    CONSTRAINT ck_posting_type
        CHECK (postingtype IN ('DEBIT','CREDIT')),

    CONSTRAINT ck_posting_amount
        CHECK (amount > 0)
);


-- ============================================================
-- 19. LOAN_TYPE
-- ============================================================

CREATE TABLE loan_type (
    loantypeid             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loantypename           VARCHAR(100) NOT NULL UNIQUE,
    maxamount              NUMERIC(19,2) NOT NULL,
    defaultinterestrate    NUMERIC(8,4) NOT NULL,
    maxtermmonths          INTEGER NOT NULL,
    description            VARCHAR(255),
    status                 VARCHAR(20) NOT NULL DEFAULT 'Active',

    CONSTRAINT ck_loan_type_amount
        CHECK (maxamount > 0),

    CONSTRAINT ck_loan_type_interest
        CHECK (defaultinterestrate >= 0),

    CONSTRAINT ck_loan_type_term
        CHECK (maxtermmonths > 0),

    CONSTRAINT ck_loan_type_status
        CHECK (status IN ('Active','Inactive'))
);


-- ============================================================
-- 20. LOAN
-- ============================================================

CREATE TABLE loan (
    loanid            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loancode          VARCHAR(30) NOT NULL UNIQUE,
    customerid        BIGINT NOT NULL,
    branchid          INTEGER NOT NULL,
    employeeid        INTEGER NOT NULL,
    loantypeid        INTEGER NOT NULL,
    principalamount   NUMERIC(19,2) NOT NULL,
    interestrate      NUMERIC(8,4) NOT NULL,
    termmonths        INTEGER NOT NULL,
    startdate         DATE NOT NULL,
    enddate           DATE NOT NULL,
    status            VARCHAR(20) NOT NULL,

    CONSTRAINT fk_loan_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT fk_loan_branch
        FOREIGN KEY (branchid)
        REFERENCES branch(branchid),

    CONSTRAINT fk_loan_employee
        FOREIGN KEY (employeeid)
        REFERENCES employee(employeeid),

    CONSTRAINT fk_loan_type
        FOREIGN KEY (loantypeid)
        REFERENCES loan_type(loantypeid),

    CONSTRAINT ck_loan_principal
        CHECK (principalamount > 0),

    CONSTRAINT ck_loan_interest
        CHECK (interestrate >= 0),

    CONSTRAINT ck_loan_term
        CHECK (termmonths > 0),

    CONSTRAINT ck_loan_dates
        CHECK (enddate >= startdate),

    CONSTRAINT ck_loan_status
        CHECK (status IN (
            'Pending',
            'Active',
            'Paid',
            'Overdue',
            'Cancelled'
        ))
);


-- ============================================================
-- 21. REPAYMENT_SCHEDULE
-- ============================================================

CREATE TABLE repayment_schedule (
    scheduleid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loanid           BIGINT NOT NULL,
    installmentno    INTEGER NOT NULL,
    duedate          DATE NOT NULL,
    principaldue     NUMERIC(19,2) NOT NULL,
    interestdue      NUMERIC(19,2) NOT NULL,
    penaltydue       NUMERIC(19,2) NOT NULL DEFAULT 0,
    status           VARCHAR(20) NOT NULL,

    CONSTRAINT fk_schedule_loan
        FOREIGN KEY (loanid)
        REFERENCES loan(loanid),

    CONSTRAINT uq_schedule_loan
        UNIQUE (loanid, scheduleid),

    CONSTRAINT uq_schedule_installment
        UNIQUE (loanid, installmentno),

    CONSTRAINT ck_schedule_installment
        CHECK (installmentno > 0),

    CONSTRAINT ck_schedule_principal
        CHECK (principaldue >= 0),

    CONSTRAINT ck_schedule_interest
        CHECK (interestdue >= 0),

    CONSTRAINT ck_schedule_penalty
        CHECK (penaltydue >= 0),

    CONSTRAINT ck_schedule_status
        CHECK (status IN (
            'Pending',
            'Partial',
            'Paid',
            'Overdue'
        ))
);


-- ============================================================
-- 22. LOAN_PAYMENT
-- ============================================================

CREATE TABLE loan_payment (
    loanpaymentid    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loanid           BIGINT NOT NULL,
    scheduleid       BIGINT,
    paymentdate      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amountpaid       NUMERIC(19,2) NOT NULL,
    principalpaid    NUMERIC(19,2) NOT NULL,
    interestpaid     NUMERIC(19,2) NOT NULL,
    penaltyfee       NUMERIC(19,2) NOT NULL DEFAULT 0,
    paymentchannel   VARCHAR(30) NOT NULL,
    employeeid       INTEGER,
    note             VARCHAR(255),
    transactionid    BIGINT NOT NULL UNIQUE,

    CONSTRAINT fk_payment_loan
        FOREIGN KEY (loanid)
        REFERENCES loan(loanid),

    CONSTRAINT fk_payment_schedule
        FOREIGN KEY (loanid, scheduleid)
        REFERENCES repayment_schedule(loanid, scheduleid),

    CONSTRAINT fk_payment_employee
        FOREIGN KEY (employeeid)
        REFERENCES employee(employeeid),

    CONSTRAINT fk_payment_transaction
        FOREIGN KEY (transactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT ck_payment_amount
        CHECK (amountpaid > 0),

    CONSTRAINT ck_payment_principal
        CHECK (principalpaid >= 0),

    CONSTRAINT ck_payment_interest
        CHECK (interestpaid >= 0),

    CONSTRAINT ck_payment_penalty
        CHECK (penaltyfee >= 0),

    CONSTRAINT ck_payment_total
        CHECK (
            amountpaid =
            principalpaid + interestpaid + penaltyfee
        ),

    CONSTRAINT ck_payment_channel
        CHECK (paymentchannel IN ('Counter','Account','Online')),

    CONSTRAINT ck_payment_employee
        CHECK (
            (paymentchannel = 'Counter' AND employeeid IS NOT NULL)
            OR
            (paymentchannel IN ('Account','Online') AND employeeid IS NULL)
        )
);


-- ============================================================
-- 23. MODEL_VERSION
-- ============================================================

CREATE TABLE model_version (
    modelversionid   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelname        VARCHAR(100) NOT NULL,
    modeltype        VARCHAR(50) NOT NULL,
    status           VARCHAR(20) NOT NULL,
    createdat        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description      VARCHAR(255),

    CONSTRAINT ck_model_status
        CHECK (status IN ('CANDIDATE','ACTIVE','RETIRED'))
);


-- ============================================================
-- 24. RISK_ASSESSMENT
-- ============================================================

CREATE TABLE risk_assessment (
    riskassessmentid   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionid      BIGINT NOT NULL,
    modelversionid     BIGINT NOT NULL,
    riskscore          NUMERIC(8,6) NOT NULL,
    decision           VARCHAR(20) NOT NULL,
    reasonjson         JSONB,
    assessedat         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_risk_transaction
        FOREIGN KEY (transactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT fk_risk_model
        FOREIGN KEY (modelversionid)
        REFERENCES model_version(modelversionid),

    CONSTRAINT ck_risk_score
        CHECK (riskscore BETWEEN 0 AND 1),

    CONSTRAINT ck_risk_decision
        CHECK (decision IN ('ALLOW','REVIEW','BLOCK'))
);


-- ============================================================
-- 25. REVIEW_CASE
-- ============================================================

CREATE TABLE review_case (
    reviewcaseid       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionid      BIGINT NOT NULL,
    status             VARCHAR(20) NOT NULL,
    revieweruserid     INTEGER,
    createdat          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewedat         TIMESTAMP,
    reason             VARCHAR(255),

    CONSTRAINT fk_review_transaction
        FOREIGN KEY (transactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT fk_review_user
        FOREIGN KEY (revieweruserid)
        REFERENCES system_user(userid),

    CONSTRAINT ck_review_status
        CHECK (status IN (
            'OPEN',
            'IN_REVIEW',
            'APPROVED',
            'REJECTED',
            'CLOSED'
        )),

    CONSTRAINT ck_review_time
        CHECK (reviewedat IS NULL OR reviewedat >= createdat)
);


-- ============================================================
-- 26. FRAUD_LABEL_EVENT
-- ============================================================

CREATE TABLE fraud_label_event (
    fraudlabeleventid   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionid       BIGINT NOT NULL,
    label               VARCHAR(20) NOT NULL,
    labeledat           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    labelsource         VARCHAR(50) NOT NULL,
    note                VARCHAR(255),

    CONSTRAINT fk_fraud_label_transaction
        FOREIGN KEY (transactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT ck_fraud_label
        CHECK (label IN (
            'FRAUD',
            'LEGITIMATE',
            'UNKNOWN'
        ))
);


-- ============================================================
-- 27. EVENT_OUTBOX
-- ============================================================

CREATE TABLE event_outbox (
    eventoutboxid    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventkey         VARCHAR(100) NOT NULL UNIQUE,
    aggregatetype    VARCHAR(50) NOT NULL,
    aggregateid      VARCHAR(100) NOT NULL,
    eventtype        VARCHAR(100) NOT NULL,
    payloadjson      JSONB NOT NULL,
    createdat        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    publishedat      TIMESTAMP,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    CONSTRAINT ck_event_outbox_status
        CHECK (status IN ('PENDING','PUBLISHED','FAILED')),

    CONSTRAINT ck_event_outbox_time
        CHECK (publishedat IS NULL OR publishedat >= createdat)
);


-- ============================================================
-- 28. NOTIFICATION_OUTBOX
-- ============================================================

CREATE TABLE notification_outbox (
    notificationoutboxid   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customerid              BIGINT NOT NULL,
    transactionid           BIGINT,
    notificationtype        VARCHAR(50) NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    createdat               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sentat                  TIMESTAMP,

    CONSTRAINT fk_notification_customer
        FOREIGN KEY (customerid)
        REFERENCES customer(customerid),

    CONSTRAINT fk_notification_transaction
        FOREIGN KEY (transactionid)
        REFERENCES bank_transaction(transactionid),

    CONSTRAINT ck_notification_status
        CHECK (status IN ('PENDING','SENT','FAILED')),

    CONSTRAINT ck_notification_time
        CHECK (sentat IS NULL OR sentat >= createdat)
);


-- ============================================================
-- 29. AUDIT_LOG
-- ============================================================

CREATE TABLE audit_log (
    auditid        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid         INTEGER,
    entitytype     VARCHAR(50) NOT NULL,
    entityid       VARCHAR(100) NOT NULL,
    action         VARCHAR(30) NOT NULL,
    oldvalue       JSONB,
    newvalue       JSONB,
    createdat      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipaddress      VARCHAR(45),

    CONSTRAINT fk_audit_user
        FOREIGN KEY (userid)
        REFERENCES system_user(userid),

    CONSTRAINT ck_audit_action
        CHECK (action IN (
            'INSERT',
            'UPDATE',
            'DELETE',
            'STATUS_CHANGE'
        )),

    CONSTRAINT ck_audit_values
        CHECK (
            (action = 'INSERT'
                AND oldvalue IS NULL
                AND newvalue IS NOT NULL)
            OR
            (action = 'DELETE'
                AND oldvalue IS NOT NULL
                AND newvalue IS NULL)
            OR
            (action IN ('UPDATE','STATUS_CHANGE')
                AND oldvalue IS NOT NULL
                AND newvalue IS NOT NULL)
        )
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_employee_branch
    ON employee(branchid);

CREATE INDEX idx_customer_device_customer
    ON customer_device(customerid);

CREATE INDEX idx_login_customer_time
    ON login_event(customerid, logintime);

CREATE INDEX idx_bank_account_branch
    ON bank_account(branchid);

CREATE INDEX idx_account_holder_customer
    ON account_holder(customerid);

CREATE INDEX idx_transaction_date
    ON bank_transaction(transactiondate);

CREATE INDEX idx_transaction_customer_date
    ON bank_transaction(initiatedbycustomerid, transactiondate);

CREATE INDEX idx_transaction_status
    ON bank_transaction(status);

CREATE INDEX idx_transaction_device
    ON bank_transaction(deviceid);

CREATE INDEX idx_posting_transaction
    ON transaction_posting(transactionid);

CREATE INDEX idx_posting_account
    ON transaction_posting(accountid);

CREATE INDEX idx_transfer_customer_time
    ON transfer_request(customerid, requestedat);

CREATE INDEX idx_loan_customer
    ON loan(customerid);

CREATE INDEX idx_schedule_loan
    ON repayment_schedule(loanid);

CREATE INDEX idx_risk_transaction
    ON risk_assessment(transactionid);

CREATE INDEX idx_risk_score
    ON risk_assessment(riskscore);

CREATE INDEX idx_review_transaction
    ON review_case(transactionid);

CREATE INDEX idx_fraud_transaction
    ON fraud_label_event(transactionid);

CREATE INDEX idx_outbox_pending
    ON event_outbox(createdat)
    WHERE status = 'PENDING';

CREATE INDEX idx_notification_pending
    ON notification_outbox(createdat)
    WHERE status = 'PENDING';

CREATE INDEX idx_audit_entity
    ON audit_log(entitytype, entityid);

CREATE INDEX idx_audit_created
    ON audit_log(createdat);